/**
 * Always a same-origin path. In dev, Vite proxies it to the API (see
 * vite.config.ts); in production the host is expected to do the same.
 * The auth cookies are HttpOnly and set without a Domain, so they only
 * work when the API is reached through the dashboard's own origin.
 */
export const API_BASE_URL = "/api/v1"

export const API_ERROR_CODES = {
  NETWORK_ERROR: "NETWORK_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_REVOKED: "SESSION_REVOKED",
  CSRF_ORIGIN_REJECTED: "CSRF_ORIGIN_REJECTED",
  FORBIDDEN: "FORBIDDEN",
  MISSING_IDEMPOTENCY_KEY: "MISSING_IDEMPOTENCY_KEY",
  INVALID_IDEMPOTENCY_KEY: "INVALID_IDEMPOTENCY_KEY",
  IDEMPOTENCY_IN_PROGRESS: "IDEMPOTENCY_IN_PROGRESS",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  // Scheduling (FS18)
  SCHEDULE_CONFLICT: "SCHEDULE_CONFLICT",
  REQUEST_NOT_SCHEDULABLE: "REQUEST_NOT_SCHEDULABLE",
  DEVICE_ALREADY_SCHEDULED: "DEVICE_ALREADY_SCHEDULED",
  // Technician work (FS23) and part proposals
  VISIT_STATUS_CONFLICT: "VISIT_STATUS_CONFLICT",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  WORK_RESULTS_INCOMPLETE: "WORK_RESULTS_INCOMPLETE",
  WORK_NOT_APPROVED: "WORK_NOT_APPROVED",
  // Billing (FS10, FS11, FS25)
  BILLING_NOT_CONFIGURED: "BILLING_NOT_CONFIGURED",
  CURRENCY_LOCKED: "CURRENCY_LOCKED",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INVOICE_ALREADY_ISSUED: "INVOICE_ALREADY_ISSUED",
  // Technician management (FS09)
  TECHNICIAN_NOT_ACTIVATED: "TECHNICIAN_NOT_ACTIVATED",
  TECHNICIAN_ALREADY_ACTIVATED: "TECHNICIAN_ALREADY_ACTIVATED",
  INVALID_ACTIVATION_TOKEN: "INVALID_ACTIVATION_TOKEN",
} as const

/** Every response carries it; only error bodies repeat it as `error.requestId`. */
export const REQUEST_ID_HEADER = "X-Request-Id"

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES]
